# Generated by Django 5.0.2 on 2025-08-14 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha_tecnica', '0002_fichatecnica_user'),
        ('produto', '0003_alter_produto_categoria_alter_produto_estoque_minimo_and_more'),
        ('unidade', '0002_unidade_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='produto.produto')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='unidade.unidade')),
            ],
        ),
        migrations.AlterField(
            model_name='fichatecnica',
            name='insumos',
            field=models.ManyToManyField(related_name='fichas_tecnicas', to='ficha_tecnica.insumo'),
        ),
    ]
