# Generated by Django 5.0.2 on 2025-08-14 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha_tecnica', '0003_insumo_alter_fichatecnica_insumos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichatecnica',
            name='insumos',
        ),
        migrations.AddField(
            model_name='insumo',
            name='ficha_tecnica',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='ficha_tecnica.fichatecnica'),
            preserve_default=False,
        ),
    ]
