# Generated by Django 5.0.2 on 2025-08-13 17:39

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0002_categoria_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='cor',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
    ]
