# Generated by Django 5.0.2 on 2025-08-14 12:36

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0003_alter_categoria_cor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='cor',
            field=colorfield.fields.ColorField(default='blue', image_field=None, max_length=25, samples=None),
        ),
    ]
